---
name: CI Trivy Scans

on:
  workflow_call:
    inputs:
      verticals:
        required: true
        type: string

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan for ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ${{ fromJSON(inputs.verticals) }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Security Scan Image ${{ matrix.image }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/anrayliu/testmycs:${{ matrix.image }}
          severity: "CRITICAL"
          ignore-unfixed: true
          exit-code: 1
